#!/bin/bash
#http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
canonicalize_path() {
	path="$1"
	if [ -L $path ]; then
		path=$(readlink $1)
	fi
	if [ -d "$path" ]; then
        _canonicalize_dir_path "$path"
    else
        _canonicalize_file_path "$path"
    fi
}   

_canonicalize_dir_path() {
    (cd "$1" 2>/dev/null && pwd -P) 
}           

_canonicalize_file_path() {
    local dir file
    dir=$(dirname -- "$1")
    file=$(basename -- "$1")
    (cd "$dir" 2>/dev/null && printf '%s/%s\n' "$(pwd -P)" "$file")
}
SCRIPT=$(canonicalize_path $0)
BASEDIR=$(cd $(dirname $SCRIPT);pwd)
export VIM=$BASEDIR
$BASEDIR/Vim_ -g $@
