#!/bin/bash
SCRIPT=$(readlink $0)
BASEDIR=$(cd $(dirname $SCRIPT);pwd)
if [ -d ~/.vim ];then
read -p "replace ~/.vim?" -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]];then
	exit 1
fi
fi
set -x
rm -rf ~/.vim
ln -sf $BASEDIR/../Resources/vim/vimfiles ~/.vim
ln -sf $BASEDIR/GVim /usr/local/bin/gvim
ln -sf $BASEDIR/Vim /usr/local/bin/vim
ln -sf $BASEDIR/mvim /usr/local/bin/mvim
ln -sf $BASEDIR/Vim /usr/local/bin/vi
